'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'kn';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    toggleLanguage: () => void;
    t: (key: string) => string;
}

const translations = {
    // ... existing translations ...
    en: {
        welcome: 'Welcome to AgriBid',
        farmer_dashboard: 'Farmer Dashboard',
        retailer_dashboard: 'Retailer Dashboard',
        admin_dashboard: 'Admin Dashboard',
        login: 'Login',
        register: 'Register',
        logout: 'Logout',
        add_crop: 'Add Crop',
        my_crops: 'My Crops',
        search_crops: 'Search Crops',
        bid_now: 'Bid Now',
        active_bids: 'Active Bids',
        no_crops: 'You have not listed any crops yet.',
        mandi_prices: 'Karnataka Mandi Prices',
        avg_price: 'Avg Price',
        trend: 'Trend',
        income: 'Income Tracking',
        home: 'Back to Home',
        for_farmers: 'For Farmers',
        for_retailers: 'For Retailers',
        farmer_desc: 'Sell your harvest at fair prices directly to retailers.',
        retailer_desc: 'Source fresh crops with verified quality and trust scores.',
        why_choose: 'Why Choose AgriBid?',
        direct_access: 'Direct Access',
        direct_desc: 'No more middlemen. Farmers set their prices, retailers bid directly.',
        real_time_bidding: 'Real-Time Bidding',
        bidding_desc: 'Dynamic marketplace with bulk and mini-bid options for every need.',
        ai_integrity: 'AI Marketplace Integrity',
        integrity_desc: 'Detecting cartel behavior and ensuring fair price ranges for everyone.',
        about_us: 'About Us',
        terms_conditions: 'Terms & Conditions',
        privacy_policy: 'Privacy Policy',
        hero_headline: 'Sell Crops at the Right Price. Get Paid Instantly.',
        hero_subtext: 'No middlemen. No delays. No confusion.',
        get_started: 'Get Started',
        see_how_it_works: 'See How It Works',
        how_it_works: 'How It Works',
        list_crop: 'List your crop',
        list_crop_desc: 'Easily upload your harvest details from your phone.',
        buyers_bid: 'Buyers place bids',
        buyers_bid_desc: 'Buyers compete to give you the highest market price.',
        money_instantly: 'Money reaches instantly',
        money_instantly_desc: 'Once you accept a bid, payment is sent to your account.',
        protect_farmers: 'How We Protect Farmers',
        fair_price: 'Fair price checking',
        fair_price_desc: 'We analyze market trends to make sure you get a fair price.',
        group_selling: 'Group selling for small farmers',
        group_selling_desc: 'Join forces with others to sell in bulk and attract bigger buyers.',
        secure_payments: 'Secure & transparent payments',
        secure_payments_desc: 'Your money is tracked and delivered safely to you.',
        view_live_prices: 'View Live Market Prices',
        earn_more_metric: 'Farmers earn 18% more on average',
        final_cta_headline: 'Grow More. Earn Fair. Sleep Peacefully.',
        join_as_farmer: 'Join as Farmer',
        join_as_buyer: 'Join as Buyer',
        join_agribid: 'Join AgriBid',
        welcome_back: 'Welcome Back',
        email_address: 'Email Address',
        password_label: 'Password',
        i_am_a: 'I am a...',
        farmer: 'Farmer',
        retailer: 'Retailer',
        admin: 'Admin',
        business_name: 'Business Name',
        gst_id: 'GST ID',
        complete_registration: 'Complete Registration',
        registering: 'Registering...',
        logging_in: 'Logging in...',
        dont_have_account: "Don't have an account?",
        already_have_account: 'Already have an account?',
        register_here: 'Register here',
        login_here: 'Login here',
        namaste_farmer: 'Namaste, Farmer 👋',
        farm_performance: 'Your farm\'s digital performance at a glance.',
        list_new_crop: 'List New Crop',
        important_updates: 'Important Updates & New Bids',
        view_all_listings: 'View All Listings',
        total_earnings: 'Total Earnings',
        successful_bids: 'Successful Bids',
        extra_earning: 'Extra Earning',
        current_balance: 'Current Balance',
        withdraw: 'Withdraw',
        monthly_revenue: 'Monthly Revenue',
        market_demands: 'Market Demands',
        explore_full_market: 'Explore Full Market',
        recommended_crops: 'Recommended Crops for You',
        welcome_retailer: 'Welcome back, Retailer 👋',
        retailer_desc_perf: 'Monitor your purchases and active bids in one place.',
        browse_marketplace: 'Browse Marketplace',
        total_spent: 'Total Spent',
        active_bids_count: 'Active Bids',
        wallet_balance: 'Wallet Balance',
        recharge: 'Recharge',
        spending_trend: 'Monthly Spending Trend',
        market_trends: 'Market Trends',
        shop_harvest: 'Shop Today\'s Harvest',
        bidding_details: 'Bidding Details',
        list_new_crop_title: 'List New Crop',
        crop_name_label: 'Crop Name',
        bidding_type_label: 'Bidding Type',
        bulk_desc: '>20kg, Custom timing',
        mini_desc: '1-20kg, 4h duration',
        total_quantity_label: 'Total Quantity (kg)',
        start_time_label: 'Start Time',
        duration_label: 'Duration (1-10 hours)',
        quality_grade_label: 'Quality Grade',
        min_price_label: 'Min Price (per kg)',
        ai_fair_price: 'AI Fair Price Indicator',
        sidebar_dashboard: 'Dashboard',
        sidebar_my_listings: 'My Listings',
        sidebar_add_crop: 'Add New Crop',
        sidebar_income: 'Income Tracking',
        sidebar_wallet: 'Wallet & Payout',
        sidebar_reports: 'Reports & Support',
        sidebar_back_home: 'Back to Home',
        sidebar_logout: 'Logout',
        farmer_dashboard_header: 'Farmer Dashboard',
        manage_crops_desc: 'Manage your crops and bids',
        trust_score_label: 'Trust Score',
        search_placeholder: 'Search your crops...',
        filter_active: 'Filters Active',
        filters: 'Filters',
        bidding_status_label: 'Bidding Status',
        all_status: 'All Status',
        active_bidding: 'Active Bidding',
        closed_finished: 'Closed/Finished',
        all_types: 'All Types',
        bulk_bidding: 'Bulk Bidding',
        mini_bidding: 'Mini Bidding',
        apply_btn: 'Apply',
        loading_listings: 'Loading your listings...',
        no_crops_found: 'No crops found',
        no_match_filters: 'You haven\'t listed any crops matching your filters.',
        create_listing_btn: 'Create New Listing',
        live_activity: 'Live Activity',
        ends_in: 'Ends in',
        kg_available: 'kg available',
        current_high_bid: 'Current High Bid',
        starting_price: 'Starting Price',
        total_bids_label: 'Total Bids',
        live_bids_btn: 'Live Bids',
        manage_listing_btn: 'Manage Listing',
        view_details: 'View Details',
        from_listings: 'From listings',
        above_market_avg: 'Above market avg',
        last_6_months: 'Last 6 Months Data',
        no_earnings_data: 'No earnings data available',
        market_avg_label: 'Market Avg',
        start_list_btn: 'Start List',
        income_tracking_title: 'Income Tracking',
        pending_clearance: 'Pending Clearance',
        lifetime_sales: 'Lifetime sales value',
        awaiting_payment: 'Awaiting retailer payment',
        stability_score: 'Stability Score',
        income_reliability: 'Income reliability index',
        earning_trends: 'Earning Trends (Last 6 Months)',
        transaction_history: 'Transaction History',
        no_completed_sales: 'No completed sales yet.',
        crop_label: 'Crop',
        qty_column: 'Qty (kg)',
        amount_column: 'Amount',
        payment_status_column: 'Payment',
        date_column: 'Date',
        wallet_payout_title: 'Wallet & Payout',
        available_earnings: 'Available Earnings',
        funds_ready_desc: 'Funds ready for bank transfer',
        withdraw_to_bank: 'Withdraw to Bank',
        payout_amount: 'Payout Amount',
        min_amount: 'Min: ₹100',
        max_available: 'Max available',
        bank_account_title: 'Settlement Bank Account',
        acc_holder_placeholder: 'Account Holder Name',
        acc_number_placeholder: 'Bank Account Number',
        ifsc_placeholder: 'IFSC Code',
        transfer_to_bank_btn: 'Transfer to Bank',
        settlement_desc: 'Settlements are usually completed within 24-48 working hours.',
        earning_history: 'Earning History',
        recent_activity: 'Recent wallet activity',
        no_history_yet: 'No history yet',
        payout_processed_msg: 'Withdrawal request processed successfully! Funds will be settled to your bank.',
        insufficient_balance_msg: 'Insufficient balance',
        support_reports_title: 'Support & Reports',
        submit_new_report: 'Submit New Report',
        cancel_btn: 'Cancel',
        report_issue_title: 'Report an Issue',
        category_label: 'Category',
        website_issue: 'Website Bug / Problem',
        complaint_farmer: 'Complaint about a Farmer',
        complaint_retailer: 'Complaint about a Retailer',
        payment_wallet_issue: 'Payment / Wallet Issue',
        other_issue: 'Other',
        subject_label: 'Subject',
        subject_placeholder: 'Brief summary of the issue',
        description_label: 'Description',
        description_placeholder: 'Please provide details...',
        send_report_btn: 'Send Report',
        submitting_btn: 'Submitting...',
        previous_reports_title: 'Your Previous Reports',
        loading_reports: 'Loading reports...',
        no_reports_found_msg: 'No reports found.',
        admin_response: 'Admin Response',
        submitted_on: 'Submitted on',
        report_success_msg: 'Success! Your report has been submitted to the admin.',
        sidebar_marketplace: 'Marketplace',
        sidebar_active_bids: 'My Active Bids',
        sidebar_order_history: 'Order History',
        sidebar_retailer_wallet: 'Wallet',
        retailer_dashboard_header: 'Retailer Dashboard',
        manage_bidding_desc: 'Manage your bidding and orders',
        verified_retailer_label: 'Verified Retailer',
        bulk_quantity_rule: 'Bulk quantity must be above 20kg',
        mini_quantity_rule: 'Mini quantity must be 1-20kg',
        ai_price_desc_template: 'Based on recent Mandi prices for {crop} ({grade} Grade):',
        creating_listing_btn: 'Creating Listing...',
        basmati_rice_placeholder: 'e.g. Basmati Rice',
        grade_a_label: 'Grade A (Premium)',
        grade_b_label: 'Grade B (Standard)',
        grade_c_label: 'Grade C (Industrial)',
        failed_add_crop: 'Failed to add crop',
        list_crop_btn: 'List Crop for Auction',
        // Marketplace
        marketplace_title: 'Marketplace',
        search_crop_hint: 'Search crop name (e.g. Wheat, Potato)...',
        all_grades: 'All Grades',
        grade_a: 'Grade A',
        grade_b: 'Grade B',
        grade_c: 'Grade C',
        all_bid_types: 'All Bid Types',
        bulk_bids: 'Bulk Bids',
        mini_bids: 'Mini Bids',
        loading_marketplace: 'Loading marketplace...',
        no_matching_crops: 'No matching crops found.',
        adjust_filters: 'Try adjusting your search filters.',
        starts_in: 'Starts in',
        ends_in_label: 'Ends in',
        min_price_label_short: 'Min Price',
        current_highest: 'Current Highest',
        farmer_trust_score: 'Farmer Trust Score',
        verified_label: 'Verified',
        bidding_starts_at: 'Bidding starts at',
        place_bid_btn: 'Place Bid',
        placing_bid: 'Placing...',
        bid_success: 'Bid placed successfully!',
        qty_kg: 'Qty (kg)',
        price_per_kg: 'Price/kg',
        // Wallet
        my_wallet: 'My Wallet',
        secure_transactions: 'Secure 256-bit encrypted transactions',
        available_balance: 'Available Balance',
        topup_amount: 'Top-up Amount',
        deposit_funds_btn: 'Deposit Funds Now',
        processing_btn: 'Processing...',
        withdraw_amount: 'Withdraw Amount',
        min_withdrawal: 'Min: ₹100',
        max_withdrawal: 'Max available',
        settlement_details: 'Settlement Details',
        acc_holder_label: 'Account Holder Name',
        acc_number_label: 'Bank Account Number',
        ifsc_label: 'IFSC Code',
        request_withdrawal_btn: 'Request Withdrawal',
        withdrawal_time_hint: 'Funds will be credited to your account within 2-3 business days.',
        transaction_history_title: 'Transaction History',
        loading_history: 'Loading history...',
        no_transactions_found: 'No transactions found',
        wallet_activity_hint: 'Your wallet activity will appear here.',
        funds_added_success: 'Funds added successfully!',
        withdrawal_success: 'Withdrawal request processed successfully!',
        // Bids & Orders
        my_active_bids_title: 'My Active Bids',
        loading_bids: 'Loading your bids...',
        no_active_bids: 'You have no active bids.',
        browse_market_hint: 'Browse the marketplace to find fresh crops to bid on.',
        go_to_marketplace: 'Go to Marketplace',
        your_price: 'Your Price',
        status_label: 'Status',
        market_status: 'Market Status',
        auction_live: 'Auction Live',
        auction_closed: 'Closed',
        complete_payment_btn: 'Complete Payment',
        order_success_msg: 'Order successfully done!',
        order_history_title: 'Order History',
        loading_orders: 'Loading your orders...',
        no_orders_yet: 'No orders yet.',
        completed_bids_hint: 'Your successfully completed bids will appear here.',
        transaction_id: 'Transaction ID',
        view_past_orders_desc: 'View and track all your successfully completed crop purchases.',
        market_intelligence: 'AI Market Intelligence',
        market_insight_desc: 'Data-driven insights to help you grow and sell smarter.',
        last_3m_trend: '3-Month Price Trend',
        future_demand_proj: 'Future Demand Projection',
        smart_advice: 'Smart Advice',
        high_profit_potential: 'High Profit Potential',
        wait_and_sell: 'Wait & Sell (Trend Rising)',
        harvest_now: 'Harvest & Sell (Peak Price)',
        sugarcane_demand: 'Rising due to Ethanol focus',
        onion_trend: 'Seasonal shortage expected',
        wheat_advice: 'Hold stock; prices rising soon',
        growth_recommendation: 'Next Planting Recommendation',
        predicted_price: 'Predicted Price (1 Month)',
        current_mandi: 'Current Mandi Price',
        // About Page
        about_title: 'About AgriBid',
        about_mission_title: 'Our Mission',
        about_mission_desc: 'AgriBid is dedicated to revolutionizing the agricultural supply chain by connecting farmers directly with retailers. Our primary goal is to eliminate unnecessary middlemen, ensuring that farmers receive better prices for their hard work while retailers get access to fresher produce at competitive rates.',
        about_transparent_title: 'Transparent Marketplace',
        about_transparent_desc: 'We provide a transparent, bidding-based platform where every transaction is recorded and visible to the parties involved. Our real-time bidding system ensures fair market pricing based on supply and demand.',
        about_empowering_title: 'Empowering Farmers',
        about_empowering_desc: 'Through AgriBid, farmers gain access to a larger pool of buyers beyond their local markets. We provide them with the tools and data they need to make informed decisions about their crops and pricing.',
        about_vision_title: 'Our Vision',
        about_vision_desc: 'Our vision is to become the leading digital infrastructure for agriculture in India, fostering a sustainable ecosystem where technology and tradition work hand-in-hand to ensure food security and economic prosperity for the farming community.',
        about_join_btn: 'Join our community today',
        // Terms Page
        terms_1_title: '1. Acceptance of Terms',
        terms_1_desc: 'By accessing and using AgriBid, you agree to comply with and be bound by these Terms and Conditions. If you do not agree, please do not use our services.',
        terms_2_title: '2. User Registration',
        terms_2_desc: 'Users must provide accurate and complete information during registration. Farmers and retailers are responsible for maintaining the confidentiality of their accounts.',
        terms_3_title: '3. Bidding and Transactions',
        terms_3_1: 'All bids placed are binding.',
        terms_3_2: "Payments must be settled through the platform's designated wallet system or as agreed upon within platform guidelines.",
        terms_3_3: 'Platform fees may apply to successful transactions.',
        terms_4_title: '4. Quality Standards',
        terms_4_desc: 'Farmers are expected to provide accurate descriptions and high-quality images of their produce. Retailers have the right to report discrepancies in quality if the delivered produce does not match the description.',
        terms_5_title: '5. Limitation of Liability',
        terms_5_desc: 'AgriBid acts as a facilitator and is not responsible for the quality of produce or any disputes arising outside the platform\'s oversight. However, we provide a dispute resolution mechanism to support our users.',
        // Privacy Page
        privacy_collect_title: 'Data We Collect',
        privacy_collect_desc: 'We collect information necessary to facilitate transactions, including but not limited to:',
        privacy_collect_1: 'Personal identification (Name, Contact number)',
        privacy_collect_2: 'Farm details and location',
        privacy_collect_3: 'Transaction history and bidding data',
        privacy_use_title: 'How We Use Your Data',
        privacy_use_desc: 'Your data is used to:',
        privacy_use_1: 'Provide and maintain our services.',
        privacy_use_2: 'Verify user identity and prevent fraud.',
        privacy_use_3: 'Analyze market trends to provide better insights.',
        privacy_use_4: 'Facilitate communication between farmers and retailers.',
        privacy_sharing_title: 'Data Sharing',
        privacy_sharing_desc: 'We do not sell your personal data. We only share necessary information with other parties to complete a transaction (e.g., sharing a farmer\'s contact with a winning retailer).',
        privacy_rights_title: 'Your Rights',
        privacy_rights_desc: 'You have the right to access, update, or delete your personal information at any time through your profile settings. We take data security seriously and implement industry-standard measures to protect your information.',
        approved_gov: 'Approved by Indian Government',
        all_rights_reserved: 'All Rights Reserved',
        staff_access: 'STAFF ACCESS',
        join_agribid_cta: 'Join AgriBid today and get the rewards for your hard work.',
        register_free: 'Register for Free',
    },
    hi: {
        welcome: 'एग्रीबिड में स्वागत है',
        farmer_dashboard: 'किसान डैशबोर्ड',
        retailer_dashboard: 'रिटेलर डैशबोर्ड',
        admin_dashboard: 'एडमिन डैशबोर्ड',
        login: 'लॉगिन',
        register: 'पंजीकरण',
        logout: 'लॉगआउट',
        add_crop: 'नई फसल जोड़ें',
        my_crops: 'मेरी फसलें',
        search_crops: 'फसलें खोजें',
        bid_now: 'बोಲಿ लगाएं',
        active_bids: 'मेरी बोलियां',
        no_crops: 'आपने अभी तक कोई फसल सूचीबद्ध नहीं की है।',
        mandi_prices: 'ಕರ್ನಾಟಕ ಮಂಡಿ ಭಾವ',
        avg_price: 'औसत मूल्य',
        trend: 'रुझान',
        income: 'कमाई का विवरण',
        home: 'मुख्य पृष्ठ',
        for_farmers: 'किसानों के लिए',
        for_retailers: 'रिटेलरों के लिए',
        farmer_desc: 'अपनी फसल सीधे रिटेलरों को सही दामों पर बेचें।',
        retailer_desc: 'सत्यापित गुणवत्ता और विश्वास स्कोर के साथ ताजी फसलें प्राप्त करें।',
        why_choose: 'एग्रीबिड क्यों चुनें?',
        direct_access: 'सीधी पहुंच',
        direct_desc: 'कोई बिचौलिया नहीं। किसान अपनी कीमत खुद तय करते हैं।',
        real_time_bidding: 'रियल-टाइम बोली',
        bidding_desc: 'हर जरूरत के लिए थोक और मिनी-बोली विकल्पों के साथ गतिशील बाजार।',
        ai_integrity: 'एआई मार्केट ईमानदारी',
        integrity_desc: 'गुटबाजी का पता लगाना और सभी के लिए उचित मूल्य सीमा सुनिश्चित करना।',
        about_us: 'हमारे बारे में',
        terms_conditions: 'नियम और शर्तें',
        privacy_policy: 'गोपनीयता नीति',
        hero_headline: 'फसल सही दाम पर बेचें। भुगतान तुरंत पाएं।',
        hero_subtext: 'कोई बिचौलिया नहीं। कोई देरी नहीं। कोई उलझन नहीं।',
        get_started: 'शुरू करें',
        see_how_it_works: 'देखें कैसे काम करता है',
        how_it_works: 'यह कैसे काम करता है',
        list_crop: 'फसल सूचीबद्ध करें',
        list_crop_desc: 'अपने फोन से फसल का विवरण आसानी से अपलोड करें।',
        buyers_bid: 'खरीदार बोली लगाते हैं',
        buyers_bid_desc: 'खरीदार आपको बेहतर बाजार भाव देने के लिए प्रतिस्पर्धा करते हैं।',
        money_instantly: 'पैसा तुरंत पहुंचता है',
        money_instantly_desc: 'बोली स्वीकार करते ही, पैसा आपके खाते में आ जाता है।',
        protect_farmers: 'हम किसानों की रक्षा कैसे करते हैं',
        fair_price: 'सही कीमत की जांच',
        fair_price_desc: 'हम बाजार के रुझानों का विश्लेषण करते हैं ताकि आपको सही दाम मिले।',
        group_selling: 'छोटे किसानों के लिए समूह बिक्री',
        group_selling_desc: 'थोक में बेचने और बड़े खरीदारों को आकर्षित करने के लिए दूसरों के साथ जुड़ें।',
        secure_payments: 'सुरक्षित और पारदर्शी भुगतान',
        secure_payments_desc: 'आपका पैसा ट्रैक किया जाता है और सुरक्षित रूप से आप तक पहुंचाया जाता है।',
        view_live_prices: 'मंडी के भाव देखें',
        earn_more_metric: 'किसान औसतन 18% अधिक कमाते हैं',
        final_cta_headline: 'बेहतर उगाएं। सही कमाएं। सुकून से सोएं।',
        join_as_farmer: 'किसान के रूप में जुड़ें',
        join_as_buyer: 'खरीदार के रूप में जुड़ें',
        join_agribid: 'एग्रीबिड से जुड़ें',
        welcome_back: 'स्वागत है',
        email_address: 'ईमेल पता',
        password_label: 'पासवर्ड',
        i_am_a: 'मैं हूँ...',
        farmer: 'किसान',
        retailer: 'रिटेलर',
        admin: 'एडमिन',
        business_name: 'व्यवसाय का नाम',
        gst_id: 'GST आईडी',
        complete_registration: 'पंजीकरण पूरा करें',
        registering: 'पंजीकरण हो रहा है...',
        logging_in: 'लॉगइन हो रहा है...',
        dont_have_account: 'खाता नहीं है?',
        already_have_account: 'पहले से ही खाता है?',
        register_here: 'यहाँ पंजीकरण करें',
        login_here: 'यहाँ लॉगिन करें',
        namaste_farmer: 'नमस्ते, किसान भाई 👋',
        farm_performance: 'आपके फार्म का प्रदर्शन एक नज़र में।',
        list_new_crop: 'नई फसल जोड़ें',
        important_updates: 'महत्वपूर्ण अपडेट और नई बोलियां',
        view_all_listings: 'सभी लिस्टिंग देखें',
        total_earnings: 'कुल कमाई',
        successful_bids: 'सफल बोलियां',
        extra_earning: 'अतिरिक्त कमाई',
        current_balance: 'वर्तमान शेष',
        withdraw: 'पैसे निकालें',
        monthly_revenue: 'माಸಿಕ आय',
        market_demands: 'बाजार की मांग',
        explore_full_market: 'पूरा बाजार देखें',
        recommended_crops: 'आपके लिए अनुशंसित फसलें',
        welcome_retailer: 'स्वागत है, रिटेलर भाई 👋',
        retailer_desc_perf: 'अपनी खरीदारी और सक्रिय बोलियों की निगरानी एक ही स्थान पर करें।',
        browse_marketplace: 'मार्केटप्लेस देखें',
        total_spent: 'कुल खर्च',
        active_bids_count: 'सक्रिय बोलियां',
        wallet_balance: 'वॉलेट शेष',
        recharge: 'रीचार्ज करें',
        spending_trend: 'मासिक खर्च का रुझान',
        market_trends: 'बाजार के रुझान',
        shop_harvest: 'आज की फसल खरीदें',
        bidding_details: 'बोली का विवरण',
        list_new_crop_title: 'नई फसल जोड़ें',
        crop_name_label: 'फसल का नाम',
        bidding_type_label: 'बोली का प्रकार',
        bulk_desc: '>20kg, कस्टम समय',
        mini_desc: '1-20kg, 4 घंटे की अवधि',
        total_quantity_label: 'कुल मात्रा (kg)',
        start_time_label: 'शुरू होने का समय',
        duration_label: 'अवधि (1-10 घंटे)',
        quality_grade_label: 'गुणवत्ता ग्रेड',
        min_price_label: 'न्यूनतम मूल्य (प्रति kg)',
        ai_fair_price: 'AI उचित मूल्य सूचक',
        sidebar_dashboard: 'डैशबोर्ड',
        sidebar_my_listings: 'मेरी लिस्टिंग',
        sidebar_add_crop: 'नई फसल जोड़ें',
        sidebar_income: 'कमाई का विवरण',
        sidebar_wallet: 'वॉलेट और भुगतान',
        sidebar_reports: 'रिपोर्ट और सहायता',
        sidebar_back_home: 'होम पर वापस',
        sidebar_logout: 'लॉगआउट',
        farmer_dashboard_header: 'किसान डैशबोर्ड',
        manage_crops_desc: 'अपनी फसलों और बोलियों का प्रबंधन करें',
        trust_score_label: 'ट्रस्ट स्कोर',
        search_placeholder: 'अपनी फसलें खोजें...',
        filter_active: 'फ़िल्टर लागू',
        filters: 'फ़िल्टर',
        bidding_status_label: 'बोली की स्थिति',
        all_status: 'सभी स्थिति',
        active_bidding: 'सक्रिय बोली',
        closed_finished: 'बंद/समाप्त',
        all_types: 'सभी प्रकार',
        bulk_bidding: 'बल्क बोली',
        mini_bidding: 'मिनी बोली',
        apply_btn: 'लागू करें',
        loading_listings: 'आपकी लिस्टिंग लोड हो रही है...',
        no_crops_found: 'कोई फसल नहीं मिली',
        no_match_filters: 'आपके फ़िल्टर से मेल खाने वाली कोई फसल नहीं मिली।',
        create_listing_btn: 'नई लिस्टिंग बनाएं',
        live_activity: 'लाइव गतिविधि',
        ends_in: 'समाप्त होगा:',
        kg_available: 'किग्रा उपलब्ध',
        current_high_bid: 'वर्तमान उच्च बोली',
        starting_price: 'शुरुआती कीमत',
        total_bids_label: 'कुल बोलियां',
        live_bids_btn: 'लाइव बोलियां',
        manage_listing_btn: 'लिस्टिंग प्रबंधित करें',
        view_details: 'विवरण देखें',
        from_listings: 'लिस्टिंग से',
        above_market_avg: 'बाजार औसत से ऊपर',
        last_6_months: 'पिछले 6 महीने का डेटा',
        no_earnings_data: 'कमाई का डेटा उपलब्ध नहीं है',
        market_avg_label: 'बाजार औसत',
        start_list_btn: 'सूची शुरू करें',
        income_tracking_title: 'कमाई का विवरण',
        pending_clearance: 'लंबित भुगतान',
        lifetime_sales: 'कुल बिक्री मूल्य',
        awaiting_payment: 'रिटेलर भुगतान की प्रतीक्षा',
        stability_score: 'स्थिरता स्कोर',
        income_reliability: 'आय विश्वसनीयता सूचकांक',
        earning_trends: 'कमाई का रुझान (पिछले 6 महीने)',
        transaction_history: 'लेनदेन का इतिहास',
        no_completed_sales: 'अभी तक कोई बिक्री पूरी नहीं हुई।',
        crop_label: 'फसल',
        qty_column: 'मात्रा (kg)',
        amount_column: 'राशि',
        payment_status_column: 'भुगतान',
        date_column: 'तारीख',
        wallet_payout_title: 'वॉलेट और भुगतान',
        available_earnings: 'उपलब्ध कमाई',
        funds_ready_desc: 'बैंक ट्रांसफर के लिए तैयार धनराशि',
        withdraw_to_bank: 'बैंक में निकालें',
        payout_amount: 'निकासी राशि',
        min_amount: 'न्यूनतम: ₹100',
        max_available: 'अधिकतम उपलब्ध',
        bank_account_title: 'सेटलमेंट बैंक खाता',
        acc_holder_placeholder: 'खाताधारक का नाम',
        acc_number_placeholder: 'बैंक खाता संख्या',
        ifsc_placeholder: 'IFSC कोड',
        transfer_to_bank_btn: 'बैंक में ट्रांसफर करें',
        settlement_desc: 'सेटलमेंट आमतौर पर 24-48 कार्य घंटों के भीतर पूरे हो जाते हैं।',
        earning_history: 'कमाई का इतिहास',
        recent_activity: 'हालिया वॉलेट गतिविधि',
        no_history_yet: 'अभी तक कोई इतिहास नहीं है',
        payout_processed_msg: 'निकासी अनुरोध सफलतापूर्वक संसाधित किया गया! धनराशि आपके बैंक में जमा कर दी जाएगी।',
        insufficient_balance_msg: 'अपर्याप्त शेष राशि',
        support_reports_title: 'सहायता और रिपोर्ट',
        submit_new_report: 'नई रिपोर्ट भेजें',
        cancel_btn: 'रद्द करें',
        report_issue_title: 'समस्या की रिपोर्ट करें',
        category_label: 'श्रेणी',
        website_issue: 'वेबसाइट बग / समस्या',
        complaint_farmer: 'किसान के बारे में शिकायत',
        complaint_retailer: 'रिटेलर के बारे में शिकायत',
        payment_wallet_issue: 'भुगतान / वॉलेट की समस्या',
        other_issue: 'अन्य',
        subject_label: 'विषय',
        subject_placeholder: 'समस्या का संक्षिप्त विवरण',
        description_label: 'विवरण',
        description_placeholder: 'कृपया विवरण प्रदान करें...',
        send_report_btn: 'रिपोर्ट भेजें',
        submitting_btn: 'भेजा जा रहा है...',
        previous_reports_title: 'आपकी पिछली रिपोर्ट',
        loading_reports: 'रिपोर्ट लोड हो रही हैं...',
        no_reports_found_msg: 'कोई रिपोर्ट नहीं मिली।',
        admin_response: 'व्यवस्थापक की प्रतिक्रिया',
        submitted_on: 'सबमिट किया गया:',
        report_success_msg: 'सफलता! आपकी रिपोर्ट एडमिन को भेज दी गई है।',
        sidebar_marketplace: 'मार्केटप्लेस',
        sidebar_active_bids: 'मेरी सक्रिय बोलियां',
        sidebar_order_history: 'ऑर्डर इतिहास',
        sidebar_retailer_wallet: 'वॉलेट',
        retailer_dashboard_header: 'रिटेलर डैशबोर्ड',
        manage_bidding_desc: 'अपनी बोलियों और ऑर्डर का प्रबंधन करें',
        verified_retailer_label: 'सत्यापित रिटेलर',
        bulk_quantity_rule: 'बल्क मात्रा 20kg से अधिक होनी चाहिए',
        mini_quantity_rule: 'मिनी मात्रा 1-20kg होनी चाहिए',
        ai_price_desc_template: 'मंडी भावों के आधार पर {crop} ({grade} ग्रेड) के लिए:',
        creating_listing_btn: 'लिस्टिंग बना रहे हैं...',
        basmati_rice_placeholder: 'उदा. बासमती चावल',
        grade_a_label: 'ग्रेड A (प्रीमियम)',
        grade_b_label: 'ग्रेड B (मानक)',
        grade_c_label: 'ग्रेड C (औद्योगिक)',
        failed_add_crop: 'फसल जोड़ने में विफल',
        list_crop_btn: 'नीलामी के लिए फसल सूचीबद्ध करें',
        // Marketplace
        marketplace_title: 'मार्केटप्लेस',
        search_crop_hint: 'फसल का नाम खोजें (जैसे गेहूं, आलू)...',
        all_grades: 'सभी ग्रेड',
        grade_a: 'ग्रेड ए',
        grade_b: 'ग्रेड बी',
        grade_c: 'ग्रेड सी',
        all_bid_types: 'सभी बोली प्रकार',
        bulk_bids: 'थोक बोलियां',
        mini_bids: 'मिनी बोलियां',
        loading_marketplace: 'मार्केटप्लेस लोड हो रहा है...',
        no_matching_crops: 'कोई मेल खाने वाली फसल नहीं मिली।',
        adjust_filters: 'अपने सर्च फिल्टर को एडजस्ट करने का प्रयास करें।',
        starts_in: 'शुरू होगा:',
        ends_in_label: 'समाप्त होगा:',
        min_price_label_short: 'न्यूनतम मूल्य',
        current_highest: 'वर्तमान उच्चतम',
        farmer_trust_score: 'किसान विश्वास स्कोर',
        verified_label: 'सत्यापित',
        bidding_starts_at: 'बोली शुरू होगी:',
        place_bid_btn: 'बोली लगाएं',
        placing_bid: 'बोली लगाई जा रही है...',
        bid_success: 'बोली सफलतापूर्वक लगाई गई!',
        qty_kg: 'मात्रा (किग्रा)',
        price_per_kg: 'मूल्य/किग्रा',
        // Wallet
        my_wallet: 'मेरा वॉलेट',
        secure_transactions: 'सुरक्षित 256-बिट एन्क्रिप्टेड लेनदेन',
        available_balance: 'कुल राशि',
        topup_amount: 'पैसे जोड़ें',
        deposit_funds_btn: 'अभी पैसे जोड़ें',
        processing_btn: 'प्रोसेसिंग...',
        withdraw_amount: 'पैसे निकालें',
        min_withdrawal: 'न्यूनतम: ₹100',
        max_withdrawal: 'अधिकतम उपलब्ध',
        settlement_details: 'बैंक विवरण',
        acc_holder_label: 'खाताधारक का नाम',
        acc_number_label: 'बैंक खाता संख्या',
        ifsc_label: 'IFSC कोड',
        request_withdrawal_btn: 'निकासी का अनुरोध करें',
        withdrawal_time_hint: 'पैसे 2-3 कार्य दिवसों के भीतर आपके खाते में जमा कर दिए जाएंगे।',
        transaction_history_title: 'लेनदेन का इतिहास',
        loading_history: 'इतिहास लोड हो रहा है...',
        no_transactions_found: 'कोई लेनदेन नहीं मिला',
        wallet_activity_hint: 'आपकी वॉलेट गतिविधियाँ यहाँ दिखाई देंगी।',
        funds_added_success: 'पैसे सफलतापूर्वक जुड़ गए!',
        withdrawal_success: 'निकासी अनुरोध सफलतापूर्वक संसाधित किया गया!',
        // Bids & Orders
        my_active_bids_title: 'मेरी सक्रिय बोलियां',
        loading_bids: 'आपकी बोलियां लोड हो रही हैं...',
        no_active_bids: 'आपकी कोई सक्रिय बोली नहीं है।',
        browse_market_hint: 'बोली लगाने के लिए मार्केटप्लेस में ताज़ा फसलें खोजें।',
        go_to_marketplace: 'मार्केटप्लेस पर जाएं',
        your_price: 'आपका मूल्य',
        status_label: 'स्थिति',
        market_status: 'बाजार की स्थिति',
        auction_live: 'नीलामी लाइव है',
        auction_closed: 'बंद',
        complete_payment_btn: 'भुगतान पूरा करें',
        order_success_msg: 'ऑर्डर सफलतापूर्वक पूरा हुआ!',
        order_history_title: 'ऑर्डर इतिहास',
        loading_orders: 'आपके ऑर्डर लोड हो रहे हैं...',
        no_orders_yet: 'अभी तक कोई ऑर्डर नहीं।',
        completed_bids_hint: 'आपकी सफलतापूर्वक पूरी की गई बोलियां यहाँ दिखाई देंगी।',
        transaction_id: 'लेनदेन आईडी',
        view_past_orders_desc: 'अपनी सफलतापूर्वक पूर्ण की गई फसल खरीद को देखें और ट्रैक करें।',
        market_intelligence: 'AI मार्केट इंटेलिजेंस',
        market_insight_desc: 'आपको बेहतर खेती और बिक्री में मदद करने के लिए डेटा-आधारित अंतर्दृष्टि।',
        last_3m_trend: '3 महीने के मूल्य का रुझान',
        future_demand_proj: 'भविष्य की मांग का अनुमान',
        smart_advice: 'स्मार्ट सलाह',
        high_profit_potential: 'उच्च लाभ की संभावना',
        wait_and_sell: 'रुकें और बेचें (रुझान बढ़ रहा है)',
        harvest_now: 'काटें और बेचें (उच्चतम मूल्य)',
        sugarcane_demand: 'इथेनॉल योजना के कारण मांग बढ़ रही है',
        onion_trend: 'मौसमी कमी की उम्मीद',
        wheat_advice: 'स्टॉक रखें; कीमतें जल्द ही बढ़ेंगी',
        growth_recommendation: 'अगली बुवाई के लिए सिफारिश',
        predicted_price: 'अनुमानित मूल्य (अगले महीने)',
        current_mandi: 'वर्तमान मंडी भाव',
        // About Page
        about_title: 'एग्रीबिड के बारे में',
        about_mission_title: 'हमारा मिशन',
        about_mission_desc: 'एग्रीबिड किसानों को सीधे रिटेलरों (व्यापारियों) से जोड़कर कृषि आपूर्ति श्रृंखला में क्रांति लाने के लिए समर्पित है। हमारा प्राथमिक लक्ष्य अनावश्यक बिचौलियों को खत्म करना है, यह सुनिश्चित करना कि किसानों को उनकी कड़ी मेहनत के लिए बेहतर मूल्य मिले, जबकि रिटेलरों को प्रतिस्पर्धी दरों पर ताजी उपज मिले।',
        about_transparent_title: 'पारदर्शी मार्केटप्लेस',
        about_transparent_desc: 'हम एक पारदर्शी, बोली-आधारित मंच प्रदान करते हैं जहाँ हर लेनदेन रिकॉर्ड किया जाता है और शामिल पक्षों को दिखाई देता है। हमारा रियल-टाइम बोली सिस्टम आपूर्ति और मांग के आधार पर उचित बाजार मूल्य सुनिश्चित करता है।',
        about_empowering_title: 'किसानों का सशक्तिकरण',
        about_empowering_desc: 'एग्रीबिड के माध्यम से, किसानों को उनके स्थानीय बाजारों से परे खरीदारों के एक बड़े समूह तक पहुँच मिलती है। हम उन्हें अपनी फसलों और मूल्य निर्धारण के बारे में सूचित निर्णय लेने के लिए आवश्यक उपकरण और डेटा प्रदान करते हैं।',
        about_vision_title: 'हमारा विजन',
        about_vision_desc: 'हमारा विजन भारत में कृषि के लिए अग्रणी डिजिटल बुनियादी ढांचा बनना है, एक ऐसा टिकाऊ पारिस्थितिकी तंत्र बनाना जहाँ तकनीक और परंपरा मिलकर काम करें ताकि खेती समुदाय के लिए खाद्य सुरक्षा और आर्थिक समृद्धि सुनिश्चित हो सके।',
        about_join_btn: 'आज ही हमारे समुदाय से जुड़ें',
        // Terms Page
        terms_1_title: '1. शर्तों की स्वीकृति',
        terms_1_desc: 'एग्रीबिड का उपयोग करके, आप इन नियमों और शर्तों का पालन करने और उनसे बाध्य होने के लिए सहमत होते हैं। यदि आप सहमत नहीं हैं, तो कृपया हमारी सेवाओं का उपयोग न करें।',
        terms_2_title: '2. उपयोगकर्ता पंजीकरण',
        terms_2_desc: 'उपयोगकर्ताओं को पंजीकरण के दौरान सटीक और पूरी जानकारी प्रदान करनी चाहिए। किसान और रिटेलर अपने खातों की गोपनीयता बनाए रखने के लिए जिम्मेदार हैं।',
        terms_3_title: '3. बोली और लेनदेन',
        terms_3_1: 'लगाई गई सभी बोलियां बाध्यकारी हैं।',
        terms_3_2: 'भुगतान प्लेटफ़ॉर्म के निर्धारित वॉलेट सिस्टम के माध्यम से या प्लेटफ़ॉर्म दिशानिर्देशों के भीतर सहमति के अनुसार किया जाना चाहिए।',
        terms_3_3: 'सफल लेनदेन पर प्लेटफ़ॉर्म शुल्क लागू हो सकता है।',
        terms_4_title: '4. गुणवत्ता मानक',
        terms_4_desc: 'किसानों से अपनी उपज का सटीक विवरण और उच्च गुणवत्ता वाली छवियां प्रदान करने की अपेक्षा की जाती है। यदि वितरित उपज विवरण से मेल नहीं खाती है, तो रिटेलरों को गुणवत्ता में विसंगतियों की रिपोर्ट करने का अधिकार है।',
        terms_5_title: '5. दायित्व की सीमा',
        terms_5_desc: 'एग्रीबिड एक सूत्रधार के रूप में कार्य करता है और उपज की गुणवत्ता या प्लेटफ़ॉर्म की निगरानी के बाहर उत्पन्न होने वाले किसी भी विवाद के लिए जिम्मेदार नहीं है। हालाँकि, हम अपने उपयोगकर्ताओं की सहायता के लिए विवाद समाधान तंत्र प्रदान करते हैं।',
        // Privacy Page
        privacy_collect_title: 'डेटा जो हम एकत्र करते हैं',
        privacy_collect_desc: 'हम लेनदेन को सुगम बनाने के लिए आवश्यक जानकारी एकत्र करते हैं, जिसमें शामिल हैं लेकिन इन्हीं तक सीमित नहीं है:',
        privacy_collect_1: 'व्यक्तिगत पहचान (नाम, संपर्क नंबर)',
        privacy_collect_2: 'फार्म विवरण और स्थान',
        privacy_collect_3: 'लेनदेन का इतिहास और बोली डेटा',
        privacy_use_title: 'हम आपके डेटा का उपयोग कैसे करते हैं',
        privacy_use_desc: 'आपके डेटा का उपयोग किया जाता है:',
        privacy_use_1: 'हमारी सेवाएं प्रदान करने और बनाए रखने के लिए।',
        privacy_use_2: 'उपयोगकर्ता की पहचान सत्यापित करने और धोखाधड़ी रोकने के लिए।',
        privacy_use_3: 'बेहतर अंतर्दष्टि प्रदान करने के लिए बाजार के रुझानों का विश्लेषण करने के लिए।',
        privacy_use_4: 'किसानों और रिटेलरों के बीच संचार की सुविधा के लिए।',
        privacy_sharing_title: 'डेटा साझा करना',
        privacy_sharing_desc: 'हम आपका व्यक्तिगत डेटा नहीं बेचते हैं। हम लेनदेन पूरा करने के लिए केवल अन्य पक्षों के साथ आवश्यक जानकारी साझा करते हैं (उदाहरण के लिए, जीतने वाले रिटेलर के साथ किसान का संपर्क साझा करना)।',
        privacy_rights_title: 'आपके अधिकार',
        privacy_rights_desc: 'आपको अपनी प्रोफ़ाइल सेटिंग्स के माध्यम से किसी भी समय अपनी व्यक्तिगत जानकारी तक पहुँचने, अपडेट करने या हटाने का अधिकार है। हम डेटा सुरक्षा को गंभीरता से लेते हैं और आपकी जानकारी की सुरक्षा के लिए उद्योग-मानक उपाय लागू करते हैं।',
        approved_gov: 'भारत सरकार द्वारा अनुमोदित',
        all_rights_reserved: 'सर्वाधिकार सुरक्षित',
        staff_access: 'कर्मचारी लॉगिन',
        join_agribid_cta: 'आज ही एग्रीबिड से जुड़ें और अपनी मेहनत का फल पाएं।',
        register_free: 'फ्री में रजिस्टर करें',
    },
    kn: {
        welcome: 'AgriBid ಗೆ ಸುಸ್ವಾಗತ',
        farmer_dashboard: 'ರೈತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        retailer_dashboard: 'ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        admin_dashboard: 'ನಿರ್ವಾಹಕರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        login: 'ಲಾಗಿನ್',
        register: 'ನೋಂದಣಿ',
        logout: 'ಲಾಗ್‌ಔಟ್',
        add_crop: 'ಹೊಸ ಬೆಳೆ ಸೇರಿಸಿ',
        my_crops: 'ನನ್ನ ಬೆಳೆಗಳು',
        search_crops: 'ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ',
        bid_now: 'ಈಗ ಬಿಡ್ ಮಾಡಿ',
        active_bids: 'ನನ್ನ ಬಿಡ್‌ಗಳು',
        no_crops: 'ನೀವು ಇನ್ನು ಯಾವುದೇ ಬೆಳೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿಲ್ಲ.',
        mandi_prices: 'ಕರ್ನಾಟಕ ಮಂಡಿ ಬೆಲೆಗಳು',
        avg_price: 'ಸರಾಸರಿ ಬೆಲೆ',
        trend: 'ಪ್ರವೃತ್ತಿ',
        income: 'ಆದಾಯದ ವಿವರ',
        home: 'ಮುಖಪುಟ',
        for_farmers: 'ರೈತರಿಗಾಗಿ',
        for_retailers: 'ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರಿಗಾಗಿ',
        farmer_desc: 'ನಿಮ್ಮ ಬೆಳೆಯನ್ನು ನೇರವಾಗಿ ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರಿಗೆ ನ್ಯಾಯಯುತ ಬೆಲೆಯಲ್ಲಿ ಮಾರಿ.',
        retailer_desc: 'ಪರಿಶೀಲಿಸಿದ ಗುಣಮಟ್ಟದ ಹೊಸ ಬೆಳೆಗಳನ್ನು ಖರೀದಿಸಿ.',
        why_choose: 'AgriBid ಅನ್ನು ಏಕೆ ಆರಿಸಬೇಕು?',
        direct_access: 'ನೇರ ಪ್ರವೇಶ',
        direct_desc: 'ಯಾವುದೇ ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ. ರೈತರು ತಮ್ಮ ಬೆಲೆಯನ್ನು ನಿಗದಿಪಡಿಸುತ್ತಾರೆ.',
        real_time_bidding: 'ರಿಯಲ್-ಟೈಮ್ ಬಿಡ್ಡಿಂಗ್',
        bidding_desc: 'ಬೃಹತ್ ಮತ್ತು ಮಿನಿ-ಬಿಡ್ ಆಯ್ಕೆಗಳೊಂದಿಗೆ ಕ್ರಿಯಾತ್ಮಕ ಮಾರುಕಟ್ಟೆ.',
        ai_integrity: 'AI ಮಾರುಕಟ್ಟೆ ಸಮಗ್ರತೆ',
        integrity_desc: 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಶ್ರೇಣಿಯನ್ನು ಖಚಿತಪಡಿಸುವುದು.',
        about_us: 'ನಮ್ಮ ಬಗ್ಗೆ',
        terms_conditions: 'ನಿಯಮಗಳು ಮತ್ತು ನಿಬಂಧನೆಗಳು',
        privacy_policy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
        hero_headline: 'ಸರಿಯಾದ ಬೆಲೆಗೆ ಬೆಳೆ ಮಾರಿ. ತಕ್ಷಣ ಹಣ ಪಡೆಯಿರಿ.',
        hero_subtext: 'ಯಾವುದೇ ಮಧ್ಯವರ್ತಿಗಳಿಲ್ಲ. ಯಾವುದೇ ವಿಳಂಬವಿಲ್ಲ.',
        get_started: 'ಪ್ರಾರಂಭಿಸಿ',
        see_how_it_works: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ನೋಡಿ',
        how_it_works: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
        list_crop: 'ಬೆಳೆಯನ್ನು ಪಟ್ಟಿ ಮಾಡಿ',
        list_crop_desc: 'ನಿಮ್ಮ ಫೋನ್‌ನಿಂದ ವಿವರಗಳನ್ನು ಸುಲಭವಾಗಿ ಸಲ್ಲಿಕೆ ಮಾಡಿ.',
        buyers_bid: 'ಖರೀದಿದಾರರ ಬಿಡ್ಡಿಂಗ್',
        buyers_bid_desc: 'ಉತ್ತಮ ಬೆಲೆ ನೀಡಲು ಖರೀದಿದಾರರ ನಡುವೆ ಸ್ಪರ್ಧೆ.',
        money_instantly: 'ಹಣ ತಕ್ಷಣ ತಲುಪುತ್ತದೆ',
        money_instantly_desc: 'ಬಿಡ್ ಒಪ್ಪಿಕೊಂಡ ತಕ್ಷಣ, ಹಣ ನಿಮ್ಮ ಖಾತೆಗೆ ಬರುತ್ತದೆ.',
        protect_farmers: 'ನಾವು ರೈತರನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತೇವೆ',
        fair_price: 'ನ್ಯಾಯಯುತ ಬೆಲೆ ತಪಾಸಣೆ',
        fair_price_desc: 'ಸರಿಯಾದ ಬೆಲೆ ಸಿಗುವಂತೆ ನಾವು ಮಾರುಕಟ್ಟೆಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತೇವೆ.',
        group_selling: 'ಸಣ್ಣ ರೈತರಿಗೆ ಗುಂಪು ಮಾರಾಟ',
        group_selling_desc: 'ಬೃಹತ್ ಪ್ರಮಾಣದಲ್ಲಿ ಮಾರಾಟ ಮಾಡಲು ಇತರರೊಂದಿಗೆ ಸೇರಿಕೊಳ್ಳಿ.',
        secure_payments: 'ಸುರಕ್ಷಿತ ಪಾವತಿಗಳು',
        secure_payments_desc: 'ನಿಮ್ಮ ಹಣವು ಸುರಕ್ಷಿತವಾಗಿ ನಿಮ್ಮನ್ನು ತಲುಪುತ್ತದೆ.',
        view_live_prices: 'ಲೈವ್ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ನೋಡಿ',
        earn_more_metric: 'ರೈತರು ಸರಾಸರಿ 18% ಹೆಚ್ಚು ಗಳಿಸುತ್ತಾರೆ',
        final_cta_headline: 'ಹೆಚ್ಚು ಬೆಳೆಯಿರಿ. ನ್ಯಾಯಯುತವಾಗಿ ಗಳಿಸಿ. ನೆಮ್ಮದಿಯಿಂದ ಇರಿ.',
        join_as_farmer: 'ರೈತರಾಗಿ ಸೇರಿ',
        join_as_buyer: 'ಖರೀದಿದಾರರಾಗಿ ಸೇರಿ',
        join_agribid: 'AgriBid ಗೆ ಸೇರಿ',
        welcome_back: 'ಮರಳಿ ಸುಸ್ವಾಗತ',
        email_address: 'ಇಮೇಲ್ ವಿಳಾಸ',
        password_label: 'ಪಾಸ್‌ವರ್ಡ್',
        i_am_a: 'ನಾನು ಒಬ್ಬ...',
        farmer: 'ರೈತ',
        retailer: 'ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರ',
        admin: 'ನಿರ್ವಾಹಕ',
        business_name: 'ವ್ಯವಹಾರದ ಹೆಸರು',
        gst_id: 'GST ID',
        complete_registration: 'ನೋಂದಣಿ ಪೂರ್ಣಗೊಳಿಸಿ',
        registering: 'ನೋಂದಣಿ ಆಗುತ್ತಿದೆ...',
        logging_in: 'ಲಾಗಿನ್ ಆಗುತ್ತಿದೆ...',
        dont_have_account: 'ಖಾತೆ ಇಲ್ಲವೇ?',
        already_have_account: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
        register_here: 'ಇಲ್ಲಿ ನೋಂದಾಯಿಸಿ',
        login_here: 'ಇಲ್ಲಿ ಲಾಗಿನ್ ಮಾಡಿ',
        namaste_farmer: 'ನಮಸ್ತೆ, ರೈತ ಬಂಧು 👋',
        farm_performance: 'ನಿಮ್ಮ ವಿವರಗಳು ಒಂದು ನೋಟದಲ್ಲಿ.',
        list_new_crop: 'ಹೊಸ ಬೆಳೆ ಪಟ್ಟಿ ಮಾಡಿ',
        important_updates: 'ಪ್ರಮುಖ ನವೀಕರಣಗಳು ಮತ್ತು ಹೊಸ ಬಿಡ್ಗಳು',
        view_all_listings: 'ಎಲ್ಲಾ ಪಟ್ಟಿಗಳನ್ನು ನೋಡಿ',
        total_earnings: 'ಒಟ್ಟು ಗಳಿಕೆ',
        successful_bids: 'ಯಶಸ್ವಿ ಬಿಡ್ಗಳು',
        extra_earning: 'ಹೆಚ್ಚುವರಿ ಗಳಿಕೆ',
        current_balance: 'ಪ್ರಸ್ತುತ ಬಾಕಿ',
        withdraw: 'ಹಣ ಪಡೆಯಿರಿ',
        monthly_revenue: 'ಮಾಸಿಕ ಆದಾಯ',
        market_demands: 'ಮಾರುಕಟ್ಟೆ ಬೇಡಿಕೆಗಳು',
        explore_full_market: 'ಸಂಪೂರ್ಣ ಮಾರುಕಟ್ಟೆ ನೋಡಿ',
        recommended_crops: 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾದ ಬೆಳೆಗಳು',
        welcome_retailer: 'ಮರಳಿ ಸುಸ್ವಾಗತ, ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರೇ 👋',
        retailer_desc_perf: 'ನಿಮ್ಮ ಖರೀದಿ ಮತ್ತು ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳನ್ನು ಒಂದೇ ಕಡೆ ನೋಡಿ.',
        browse_marketplace: 'ಮಾರುಕಟ್ಟೆಯನ್ನು ವೀಕ್ಷಿಸಿ',
        total_spent: 'ಒಟ್ಟು ಖರ್ಚು',
        active_bids_count: 'ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳು',
        wallet_balance: 'ವ್ಯಾಲೆಟ್ ಬಾಕಿ',
        recharge: 'ರೀಚಾರ್ಜ್',
        spending_trend: 'ಮಾಸಿಕ ಖರ್ಚಿನ ಪ್ರವೃತ್ತಿ',
        market_trends: 'ಮಾರುಕಟ್ಟೆ ಪ್ರವೃತ್ತಿಗಳು',
        shop_harvest: 'ಇಂದಿನ ಬೆಳೆಯನ್ನು ಖರೀದಿಸಿ',
        bidding_details: 'ಬಿಡ್ಡಿಂಗ್ ವಿವರಗಳು',
        list_new_crop_title: 'ಹೊಸ ಬೆಳೆ ಪಟ್ಟಿ ಮಾಡಿ',
        crop_name_label: 'ಬೆಳೆ ಹೆಸರು',
        bidding_type_label: 'ಬಿಡ್ಡಿಂಗ್ ವಿಧ',
        bulk_desc: '>20kg, ಕಸ್ಟಮ್ ಸಮಯ',
        mini_desc: '1-20kg, 4ಗಂ ಅವಧಿ',
        total_quantity_label: 'ಒಟ್ಟು ಪ್ರಮಾಣ (kg)',
        start_time_label: 'ಪ್ರಾರಂಭದ ಸಮಯ',
        duration_label: 'ಅವಧಿ (1-10 ಗಂಟೆಗಳು)',
        quality_grade_label: 'ಗುಣಮಟ್ಟದ ದರ್ಜೆ',
        min_price_label: 'ಕನಿಷ್ಠ ಬೆಲೆ (ಪ್ರತಿ ಕೆಜಿ)',
        ai_fair_price: 'AI ನ್ಯಾಯಯುತ ಬೆಲೆ ಸೂಚಕ',
        sidebar_dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        sidebar_my_listings: 'ನನ್ನ ಪಟ್ಟಿಗಳು',
        sidebar_add_crop: 'ಹೊಸ ಬೆಳೆ ಸೇರಿಸಿ',
        sidebar_income: 'ಆದಾಯ ಟ್ರ್ಯಾಕಿಂಗ್',
        sidebar_wallet: 'ವ್ಯಾಲೆಟ್ ಮತ್ತು ಪಾವತಿ',
        sidebar_reports: 'ವರದಿಗಳು ಮತ್ತು ಬೆಂಬಲ',
        sidebar_back_home: 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
        sidebar_logout: 'ಲಾಗ್‌ಔಟ್',
        farmer_dashboard_header: 'ರೈತರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        manage_crops_desc: 'ನಿಮ್ಮ ಬೆಳೆಗಳು ಮತ್ತು ಬಿಡ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        trust_score_label: 'ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಕೋರ್',
        search_placeholder: 'ನಿಮ್ಮ ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ...',
        filter_active: 'ಫಿಲ್ಟರ್‌ಗಳು ಸಕ್ರಿಯವಾಗಿವೆ',
        filters: 'ಫಿಲ್ಟರ್‌ಗಳು',
        bidding_status_label: 'ಬಿಡ್ಡಿಂಗ್ ಸ್ಥಿತಿ',
        all_status: 'ಎಲ್ಲಾ ಸ್ಥಿತಿ',
        active_bidding: 'ಸಕ್ರಿಯ ಬಿಡ್ಡಿಂಗ್',
        closed_finished: 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
        all_types: 'ಎಲ್ಲಾ ವಿಧಗಳು',
        bulk_bidding: 'ಬೃಹತ್ ಬಿಡ್ಡಿಂಗ್',
        mini_bidding: 'ಮಿನಿ ಬಿಡ್ಡಿಂಗ್',
        apply_btn: 'ಅನ್ವಯಿಸಿ',
        loading_listings: 'ನಿಮ್ಮ ಪಟ್ಟಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        no_crops_found: 'ಯಾವುದೇ ಬೆಳೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        no_match_filters: 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಹೊಂದಿಕೆಯಾಗುವ ಯಾವುದೇ ಬೆಳೆ ಪಟ್ಟಿ ಇಲ್ಲ.',
        create_listing_btn: 'ಹೊಸ ಪಟ್ಟಿ ರಚಿಸಿ',
        live_activity: 'ಲೈವ್ ಚಟುವಟಿಕೆ',
        ends_in: 'ಮುಕ್ತಾಯ ಸಮಯ:',
        kg_available: 'ಕೆಜಿ ಲಭ್ಯವಿದೆ',
        current_high_bid: 'ಪ್ರಸ್ತುತ ಉನ್ನತ ಬಿಡ್',
        starting_price: 'ಪ್ರಾರಂಭದ ಬೆಲೆ',
        total_bids_label: 'ಒಟ್ಟು ಬಿಡ್‌ಗಳು',
        live_bids_btn: 'ಲೈವ್ ಬಿಡ್‌ಗಳು',
        manage_listing_btn: 'ಪಟ್ಟಿ ನಿರ್ವಹಿಸಿ',
        view_details: 'ವಿವರ ನೋಡಿ',
        from_listings: 'ಪಟ್ಟಿಗಳಿಂದ',
        above_market_avg: 'ಮಾರುಕಟ್ಟೆ ಸರಾಸರಿಗಿಂತ ಹೆಚ್ಚು',
        last_6_months: 'ಕಳೆದ 6 ತಿಂಗಳ ಡೇಟಾ',
        no_earnings_data: 'ಗಳಿಕೆಯ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ',
        market_avg_label: 'ಮಾರುಕಟ್ಟೆ ಸರಾಸರಿ',
        start_list_btn: 'ಪಟ್ಟಿ ಪ್ರಾರಂಭಿಸಿ',
        income_tracking_title: 'ಆದಾಯ ಟ್ರ್ಯಾಕಿಂಗ್',
        pending_clearance: 'ಬಾಕಿ ಇರುವ ಪಾವತಿ',
        lifetime_sales: 'ಒಟ್ಟು ಮಾರಾಟ ಮೌಲ್ಯ',
        awaiting_payment: 'ಚಿಲ್ಲರೆ ಪಾವತಿಗಾಗಿ ಕಾಯಲಾಗುತ್ತಿದೆ',
        stability_score: 'ಸ್ಥಿರತೆ ಸ್ಕೋರ್',
        income_reliability: 'ಆದಾಯದ ವಿಶ್ವಾಸಾರ್ಹತೆ ಸೂಚ್ಯಂಕ',
        earning_trends: 'ಗಳಿಕೆಯ ಪ್ರವೃತ್ತಿ (ಕಳೆದ 6 ತಿಂಗಳು)',
        transaction_history: 'ವಹಿವಾಟಿನ ಇತಿಹಾಸ',
        no_completed_sales: 'ಇನ್ನೂ ಯಾವುದೇ ಮಾರಾಟ ಪೂರ್ಣಗೊಂಡಿಲ್ಲ.',
        crop_label: 'ಬೆಳೆ',
        qty_column: 'ಪ್ರಮಾಣ (ಕೆಜಿ)',
        amount_column: 'ಮೊತ್ತ',
        payment_status_column: 'ಪಾವತಿ',
        date_column: 'ದಿನಾಂಕ',
        wallet_payout_title: 'ವ್ಯಾಲೆಟ್ ಮತ್ತು ಪಾವತಿ',
        available_earnings: 'ಲಭ್ಯವಿರುವ ಗಳಿಕೆ',
        funds_ready_desc: 'ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆಗೆ ಹಣ ಸಿದ್ಧವಾಗಿದೆ',
        withdraw_to_bank: 'ಬ್ಯಾಂಕ್‌ಗೆ ಹಿಂಪಡೆಯಿರಿ',
        payout_amount: 'ಪಾವತಿ ಮೊತ್ತ',
        min_amount: 'ಕನಿಷ್ಠ: ₹100',
        max_available: 'ಗರಿಷ್ಠ ಲಭ್ಯವಿರುವ ಮೊತ್ತ',
        bank_account_title: 'ಪಾವತಿ ಬ್ಯಾಂಕ್ ಖಾತೆ',
        acc_holder_placeholder: 'ಖಾತೆದಾರರ ಹೆಸರು',
        acc_number_placeholder: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
        ifsc_placeholder: 'IFSC ಕೋಡ್',
        transfer_to_bank_btn: 'ಬ್ಯಾಂಕ್‌ಗೆ ವರ್ಗಾಯಿಸಿ',
        settlement_desc: 'ಪಾವತಿಗಳು ಸಾಮಾನ್ಯವಾಗಿ 24-48 ಕೆಲಸದ ಅವಧಿಯೊಳಗೆ ಪೂರ್ಣಗೊಳ್ಳುತ್ತವೆ.',
        earning_history: 'ಗಳಿಕೆಯ ಇತಿಹಾಸ',
        recent_activity: 'ಇತ್ತೀಚಿನ ವ್ಯಾಲೆಟ್ ಚಟುವಟಿಕೆ',
        no_history_yet: 'ಇನ್ನೂ ಯಾವುದೇ ಇತಿಹಾಸವಿಲ್ಲ',
        payout_processed_msg: 'ಹಿಂತೆಗೆದುಕೊಳ್ಳುವ ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗಿದೆ! ಹಣ ನಿಮ್ಮ ಬ್ಯಾಂಕ್‌ಗೆ ಜಮೆಯಾಗಲಿದೆ.',
        insufficient_balance_msg: 'ಅಪರ್ಯಾಪ್ತ ಬಾಕಿ',
        support_reports_title: 'ಬೆಂಬಲ ಮತ್ತು ವರದಿಗಳು',
        submit_new_report: 'ಹೊಸ ವರದಿ ಸಲ್ಲಿಸಿ',
        cancel_btn: 'ರದ್ದುಮಾಡಿ',
        report_issue_title: 'ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
        category_label: 'ವರ್ಗ',
        website_issue: 'ವೆಬ್‌ಸೈಟ್ ದೋಷ / ಸಮಸ್ಯೆ',
        complaint_farmer: 'ರೈತರ ಬಗ್ಗೆ ದೂರು',
        complaint_retailer: 'ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿಯ ಬಗ್ಗೆ ದೂರು',
        payment_wallet_issue: 'ಪಾವತಿ / ವ್ಯಾಲೆಟ್ ಸಮಸ್ಯೆ',
        other_issue: 'ಇತರೆ',
        subject_label: 'ವಿಷಯ',
        subject_placeholder: 'ಸಮಸ್ಯೆಯ ಸಂಕ್ಷಿಪ್ತ ವಿವರಣೆ',
        description_label: 'ವಿವರಣೆ',
        description_placeholder: 'ದಯವಿಟ್ಟು ವಿವರಗಳನ್ನು ಒದಗಿಸಿ...',
        send_report_btn: 'ವರದಿ ಕಳುಹಿಸಿ',
        submitting_btn: 'ಸಲ್ಲಿಸಲಾಗುತ್ತಿದೆ...',
        previous_reports_title: 'ನಿಮ್ಮ ಹಿಂದಿನ ವರದಿಗಳು',
        loading_reports: 'ವರದಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        no_reports_found_msg: 'ಯಾವುದೇ ವರದಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
        admin_response: 'ನಿರ್ವಾಹಕರ ಪ್ರತಿಕ್ರಿಯೆ',
        submitted_on: 'ರಂದು ಸಲ್ಲಿಸಲಾಗಿದೆ',
        report_success_msg: 'ಯಶಸ್ಸು! ನಿಮ್ಮ ವರದಿಯನ್ನು ನಿರ್ವಾಹಕರಿಗೆ ಸಲ್ಲಿಸಲಾಗಿದೆ.',
        sidebar_marketplace: 'ಮಾರುಕಟ್ಟೆ',
        sidebar_active_bids: 'ನನ್ನ ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳು',
        sidebar_order_history: 'ಸಂದೇಶ ಇತಿಹಾಸ',
        sidebar_retailer_wallet: 'ವ್ಯಾಲೆಟ್',
        retailer_dashboard_header: 'ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
        manage_bidding_desc: 'ನಿಮ್ಮ ಬಿಡ್‌ಗಳು ಮತ್ತು ಆದೇಶಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
        verified_retailer_label: 'ಪರಿಶೀಲಿಸಿದ ಮಾರಾಟಗಾರ',
        bulk_quantity_rule: 'ಬೃಹತ್ ಪ್ರಮಾಣವು 20kg ಗಿಂತ ಹೆಚ್ಚಿರಬೇಕು',
        mini_quantity_rule: 'ಮಿನಿ ಪ್ರಮಾಣವು 1-20kg ಇರಬೇಕು',
        ai_price_desc_template: 'ಮಂಡಿ ಬೆಲೆಗಳ ಆಧಾರದ ಮೇಲೆ {crop} ({grade} ದರ್ಜೆ) ಗಾಗಿ:',
        creating_listing_btn: 'ಪಟ್ಟಿ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
        basmati_rice_placeholder: 'ಉದಾ. ಬಾಸುಮತಿ ಅಕ್ಕಿ',
        grade_a_label: 'ದರ್ಜೆ A (ಪ್ರೀಮಿಯಂ)',
        grade_b_label: 'ದರ್ಜೆ B (ಸಾಮಾನ್ಯ)',
        grade_c_label: 'ದರ್ಜೆ C (ಕೈಗಾರಿಕಾ)',
        failed_add_crop: 'ಬೆಳೆ ಸೇರಿಸಲು ವಿಫಲವಾಗಿದೆ',
        list_crop_btn: 'ಹರಾಜಿಗಾಗಿ ಬೆಳೆಯನ್ನು ಪಟ್ಟಿ ಮಾಡಿ',
        // Marketplace
        marketplace_title: 'ಮಾರುಕಟ್ಟೆ',
        search_crop_hint: 'ಬೆಳೆ ಹೆಸರನ್ನು ಹುಡುಕಿ (ಉದಾ: ಗೋಧಿ, ಆಲೂಗಡ್ಡೆ)...',
        all_grades: 'ಎಲ್ಲಾ ದರ್ಜೆಗಳು',
        grade_a: 'ದರ್ಜೆ ಎ',
        grade_b: 'ದರ್ಜೆ ಬಿ',
        grade_c: 'ದರ್ಜೆ ಸಿ',
        all_bid_types: 'ಎಲ್ಲಾ ಬಿಡ್ ವಿಧಗಳು',
        bulk_bids: 'ಬೃಹತ್ ಬಿಡ್‌ಗಳು',
        mini_bids: 'ಮಿನಿ ಬಿಡ್‌ಗಳು',
        loading_marketplace: 'ಮಾರುಕಟ್ಟೆ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        no_matching_crops: 'ಯಾವುದೇ ಬೆಳೆಗಳು ಕಂಡುಬಂದಿಲ್ಲ.',
        adjust_filters: 'ಹುಡುಕಾಟ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಬದಲಿಸಲು ಪ್ರಯತ್ನಿಸಿ.',
        starts_in: 'ಪ್ರಾರಂಭವಾಗಲು ಸಮಯ:',
        ends_in_label: 'ಮುಕ್ತಾಯಗೊಳ್ಳಲು ಸಮಯ:',
        min_price_label_short: 'ಕನಿಷ್ಠ ಬೆಲೆ',
        current_highest: 'ಪ್ರಸ್ತುತ ಗರಿಷ್ಠ ಬಿಡ್',
        farmer_trust_score: 'ರೈತರ ನಂಬಿಕೆಯ ಸ್ಕೋರ್',
        verified_label: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
        bidding_starts_at: 'ಬಿಡ್ಡಿಂಗ್ ಪ್ರಾರಂಭವಾಗುವ ಸಮಯ:',
        place_bid_btn: 'ಬಿಡ್ ಮಾಡಿ',
        placing_bid: 'ಬಿಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        bid_success: 'ಬಿಡ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
        qty_kg: 'ಪ್ರಮಾಣ (ಕೆಜಿ)',
        price_per_kg: 'ಬೆಲೆ/ಕೆಜಿ',
        // Wallet
        my_wallet: 'ನನ್ನ ವ್ಯಾಲೆಟ್',
        secure_transactions: 'ಸುರಕ್ಷಿತ 256-ಬಿಟ್ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ ವಹಿವಾಟುಗಳು',
        available_balance: 'ಲಭ್ಯವಿರುವ ಬಾಕಿ',
        topup_amount: 'ಹಣ ಸೇರಿಸಿ',
        deposit_funds_btn: 'ಈಗಲೇ ಹಣ ಸೇರಿಸಿ',
        processing_btn: 'ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...',
        withdraw_amount: 'ಹಣ ಹಿಂಪಡೆಯಿರಿ',
        min_withdrawal: 'ಕನಿಷ್ಠ: ₹100',
        max_withdrawal: 'ಗರಿಷ್ಠ ಲಭ್ಯವಿರುವ ಹಣ',
        settlement_details: 'ಬ್ಯಾಂಕ್ ವಿವರಗಳು',
        acc_holder_label: 'ಖಾತೆದಾರರ ಹೆಸರು',
        acc_number_label: 'ಬ್ಯಾಂಕ್ ಖಾತೆ ಸಂಖ್ಯೆ',
        ifsc_label: 'IFSC ಕೋಡ್',
        request_withdrawal_btn: 'ಹಣ ಹಿಂಪಡೆಯಲು ವಿನಂತಿಸಿ',
        withdrawal_time_hint: 'ಹಣವು 2-3 ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ನಿಮ್ಮ ಖಾತೆಗೆ ಜಮೆಯಾಗುತ್ತದೆ.',
        transaction_history_title: 'ವಹಿವಾಟಿನ ಇತಿಹಾಸ',
        loading_history: 'ಇತಿಹಾಸ ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
        no_transactions_found: 'ಯಾವುದೇ ವಹಿವಾಟುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
        wallet_activity_hint: 'ನಿಮ್ಮ ವ್ಯಾಲೆಟ್ ಚಟುವಟಿಕೆಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.',
        funds_added_success: 'ಹಣವನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಸೇರಿಸಲಾಗಿದೆ!',
        withdrawal_success: 'ಹಣ ಹಿಂತೆಗೆದುಕೊಳ್ಳುವ ವಿನಂತಿಯನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗಿದೆ!',
        // Bids & Orders
        my_active_bids_title: 'ನನ್ನ ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳು',
        loading_bids: 'ನಿಮ್ಮ ಬಿಡ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        no_active_bids: 'ನಿಮ್ಮಲ್ಲಿ ಯಾವುದೇ ಸಕ್ರಿಯ ಬಿಡ್‌ಗಳಿಲ್ಲ.',
        browse_market_hint: 'ಬಿಡ್ ಮಾಡಲು ಮಾರುಕಟ್ಟೆಯಲ್ಲಿ ತಾಜಾ ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ.',
        go_to_marketplace: 'ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗಿ',
        your_price: 'ನಿಮ್ಮ ಬೆಲೆ',
        status_label: 'ಸ್ಥಿತಿ',
        market_status: 'ಮಾರುಕಟ್ಟೆ ಸ್ಥಿತಿ',
        auction_live: 'ಹರಾಜು ನಡೆಯುತ್ತಿದೆ',
        auction_closed: 'ಮುಕ್ತಾಯಗೊಂಡಿದೆ',
        complete_payment_btn: 'ಪಾವತಿ ಪೂರ್ಣಗೊಳಿಸಿ',
        order_success_msg: 'ಆರ್ಡರ್ ಯಶಸ್ವಿಯಾಗಿದೆ!',
        order_history_title: 'ಖರೀದಿ ಇತಿಹಾಸ',
        loading_orders: 'ನಿಮ್ಮ ಆರ್ಡರ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
        no_orders_yet: 'ಇನ್ನೂ ಯಾವುದೇ ಆರ್ಡರ್‌ಗಳಿಲ್ಲ.',
        completed_bids_hint: 'ನಿಮ್ಮ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡ ಬಿಡ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತವೆ.',
        transaction_id: 'ವಹಿವಾಟು ಐಡಿ',
        view_past_orders_desc: 'ನಿಮ್ಮ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡ ಬೆಳೆ ಖರೀದಿಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ.',
        market_intelligence: 'AI ಮಾರುಕಟ್ಟೆ ಬುದ್ಧಿವಂತಿಕೆ',
        market_insight_desc: 'ನೀವು ಉತ್ತಮವಾಗಿ ಬೆಳೆಯಲು ಮತ್ತು ಮಾರಾಟ ಮಾಡಲು ಸಹಾಯ ಮಾಡುವ ಡೇಟಾ-ಚಾಲಿತ ಒಳನೋಟಗಳು.',
        last_3m_trend: '3 ತಿಂಗಳ ಬೆಲೆ ಪ್ರವೃತ್ತಿ',
        future_demand_proj: 'ಭವಿಷ್ಯದ ಬೇಡಿಕೆಯ ಅಂದಾಜು',
        smart_advice: 'ಸ್ಮಾರ್ಟ್ ಸಲಹೆ',
        high_profit_potential: 'ಹೆಚ್ಚಿನ ಲಾಭದ ಸಂಭಾವನೆ',
        wait_and_sell: 'ಕಾಯ್ದು ಮಾರಿ (ಬೆಲೆ ಏರುತ್ತಿದೆ)',
        harvest_now: 'ತಕ್ಷಣ ಕೊಯ್ಲು ಮಾಡಿ ಮಾರಿ (ಉತ್ತಮ ಬೆಲೆ)',
        sugarcane_demand: 'ಎಥೆನಾಲ್ ಯೋಜನೆಯಿಂದ ಬೇಡಿಕೆ ಏರುತ್ತಿದೆ',
        onion_trend: 'ಕಾಲೋಚಿತ ಕೊರತೆಯ ನಿರೀಕ್ಷೆ',
        wheat_advice: 'ದಾಸ್ತಾನು ಇರಿಸಿ; ಬೆಲೆಗಳು ಶೀಘ್ರದಲ್ಲೇ ಏರಲಿವೆ',
        growth_recommendation: 'ಮುಂದಿನ ನಾಟಿ ಶಿಫಾರಸು',
        predicted_price: 'ಅಂದಾಜು ಬೆಲೆ (ಮುಂದಿನ ತಿಂಗಳು)',
        current_mandi: 'ಪ್ರಸ್ತುತ ಮಂಡಿ ಬೆಲೆ',
        // About Page
        about_title: 'AgriBid ಕುರಿತು',
        about_mission_title: 'ನಮ್ಮ ಗುರಿ (Our Mission)',
        about_mission_desc: 'AgriBid ವ್ಯವಸ್ಥೆಯು ರೈತರನ್ನು ನೇರವಾಗಿ ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುವ ಮೂಲಕ ಕೃಷಿ ಪೂರೈಕೆ ಸರಪಳಿಯಲ್ಲಿ ಕ್ರಾಂತಿ ತರಲು ಸಮರ್ಪಿತವಾಗಿದೆ. ಅನಗತ್ಯ ಮಧ್ಯವರ್ತಿಗಳನ್ನು ತೊಡೆದುಹಾಕುವುದು ನಮ್ಮ ಮುಖ್ಯ ಉದ್ದೇಶವಾಗಿದೆ. ಇದರಿಂದ ರೈತರು ತಮ್ಮ ಪರಿಶ್ರಮಕ್ಕೆ ಉತ್ತಮ ಬೆಲೆ ಪಡೆಯುತ್ತಾರೆ ಮತ್ತು ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರಿಗೆ ತಾಜಾ ಬೆಳೆಗಳು ನ್ಯಾಯಯುತ ಬೆಲೆಯಲ್ಲಿ ಸಿಗುತ್ತವೆ.',
        about_transparent_title: 'ಪಾರದರ್ಶಕ ಮಾರುಕಟ್ಟೆ',
        about_transparent_desc: 'ನಾವು ಪಾರದರ್ಶಕ ಬಿಡ್ಡಿಂಗ್ ವ್ಯವಸ್ಥೆಯನ್ನು ಒದಗಿಸುತ್ತೇವೆ, ಅಲ್ಲಿ ಪ್ರತಿಯೊಂದು ವಹಿವಾಟು ದಾಖಲಾಗುತ್ತದೆ ಮತ್ತು ಸಂಬಂಧಪಟ್ಟವರಿಗೆ ಕಾಣಿಸುತ್ತದೆ. ನಮ್ಮ ನೈಜ-ಸಮಯದ ಬಿಡ್ಡಿಂಗ್ ವ್ಯವಸ್ಥೆಯು ಮಾರುಕಟ್ಟೆಯ ಬೇಡಿಕೆಗೆ ಅನುಗುಣವಾಗಿ ಸರಿಯಾದ ಬೆಲೆಯನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ.',
        about_empowering_title: 'ರೈತರ ಸಬಲೀಕರಣ',
        about_empowering_desc: 'AgriBid ಮೂಲಕ ರೈತರು ತಮ್ಮ ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆಗಿಂತ ದೊಡ್ಡ ಮಟ್ಟದ ಖರೀದಿದಾರರನ್ನು ತಲುಪಬಹುದು. ಬೆಳೆಗಳ ಬೆಲೆ ಕುರಿತು ಸರಿಯಾದ ನಿರ್ಧಾರ ತೆಗೆದುಕೊಳ್ಳಲು ನಾವು ಅವರಿಗೆ ಅಗತ್ಯವಿರುವ ಮಾಹಿತಿ ಮತ್ತು ಡೇಟಾವನ್ನು ಒದಗಿಸುತ್ತೇವೆ.',
        about_vision_title: 'ನಮ್ಮ ದೃಷ್ಟಿ (Our Vision)',
        about_vision_desc: 'ಭಾರತದ ಕೃಷಿ ವಲಯಕ್ಕೆ ಪ್ರಮುಖ ಡಿಜಿಟಲ್ ಮೂಲಸೌಕರ್ಯವಾಗುವುದು ನಮ್ಮ ಗುರಿಯಾಗಿದೆ. ತಂತ್ರಜ್ಞಾನ ಮತ್ತು ಸಂಪ್ರದಾಯದ ಸಂಗಮದಿಂದ ರೈತ ಸಮುದಾಯಕ್ಕೆ ಆರ್ಥಿಕ ಸಮೃದ್ಧಿ ಮತ್ತು ಆಹಾರ ಭದ್ರತೆಯನ್ನು ಖಚಿತಪಡಿಸುವ ಸುಸ್ಥಿರ ವ್ಯವಸ್ಥೆಯನ್ನು ನಾವು ನಿರ್ಮಿಸುತ್ತಿದ್ದೇವೆ.',
        about_join_btn: 'ಇಂದೇ ನಮ್ಮ ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
        // Terms Page
        terms_1_title: '1. ನಿಯಮಗಳ ಒಪ್ಪಿಗೆ',
        terms_1_desc: 'AgriBid ಬಳಸುವ ಮೂಲಕ, ನೀವು ಈ ಎಲ್ಲಾ ನಿಯಮಗಳು ಮತ್ತು ನಿಬಂಧನೆಗಳನ್ನು ಪಾಲಿಸಲು ಒಪ್ಪುತ್ತೀರಿ. ನಿಮಗೆ ಇಷ್ಟವಿಲ್ಲದಿದ್ದರೆ, ದಯವಿಟ್ಟು ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಬಳಸಬೇಡಿ.',
        terms_2_title: '2. ಬಳಕೆದಾರರ ನೋಂದಣಿ',
        terms_2_desc: 'ನೋಂದಣಿ ಸಮಯದಲ್ಲಿ ಬಳಕೆದಾರರು ನಿಖರವಾದ ಮಾಹಿತಿಯನ್ನು ನೀಡಬೇಕು. ರೈತರು ಮತ್ತು ಚಿಲ್ಲರೆ ಮಾರಾಟಗಾರರು ತಮ್ಮ ಖಾತೆಯ ಗೌಪ್ಯತೆಯನ್ನು ಕಾಪಾಡಿಕೊಳ್ಳಲು ಜವಾಬ್ದಾರರಾಗಿರುತ್ತಾರೆ.',
        terms_3_title: '3. ಬಿಡ್ಡಿಂಗ್ ಮತ್ತು ವಹಿವಾಟುಗಳು',
        terms_3_1: 'ಬಿಡ್ ಮಾಡಿದ ಮೇಲೆ ಅದನ್ನು ಹಿಂಪಡೆಯಲು ಸಾಧ್ಯವಿಲ್ಲ.',
        terms_3_2: 'ಪಾವತಿಗಳನ್ನು ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನ ವ್ಯಾಲೆಟ್ ವ್ಯವಸ್ಥೆಯ ಮೂಲಕ ಅಥವಾ ಮಾರ್ಗಸೂಚಿಗಳ ಪ್ರಕಾರ ಮಾಡಬೇಕು.',
        terms_3_3: 'ಯಶಸ್ವಿ ವಹಿವಾಟುಗಳಿಗೆ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಶುಲ್ಕ ಅನ್ವಯಿಸಬಹುದು.',
        terms_4_title: '4. ಗುಣಮಟ್ಟದ ಮಾನದಂಡಗಳು',
        terms_4_desc: 'ರೈತರು ತಮ್ಮ ಬೆಳೆಗಳ ನಿಖರವಾದ ವಿವರ ಮತ್ತು ಉತ್ತಮ ಗುಣಮಟ್ಟದ ಫೋಟೋಗಳನ್ನು ನೀಡಬೇಕು. ನೀಡಿದ ವಿವರಕ್ಕೆ ಬೆಳೆ ಹೊಂದಿಕೆಯಾಗದಿದ್ದರೆ ಖರೀದಿದಾರರಿಗೆ ದೂರು ನೀಡುವ ಹಕ್ಕಿದೆ.',
        terms_5_title: '5. ಹೊಣೆಗಾರಿಕೆಯ ಮಿತಿ',
        terms_5_desc: 'AgriBid ಕೇವಲ ಮಧ್ಯಸ್ಥಿಕೆ ವಹಿಸುತ್ತದೆ. ಬೆಳೆಗಳ ಗುಣಮಟ್ಟ ಅಥವಾ ಹೊರಗಿನ ಯಾವುದೇ ವಿವಾದಗಳಿಗೆ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್ ಜವಾಬ್ದಾರರಾಗಿರುವುದಿಲ್ಲ. ಆದಾಗ್ಯೂ, ವಿವಾದ ಪರಿಹಾರಕ್ಕಾಗಿ ನಾವು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.',
        // Privacy Page
        privacy_collect_title: 'ನಾವು ಸಂಗ್ರಹಿಸುವ ಮಾಹಿತಿ',
        privacy_collect_desc: 'ವಹಿವಾಟುಗಳನ್ನು ಸುಲಭಗೊಳಿಸಲು ನಾವು ಅಗತ್ಯ ಮಾಹಿತಿಯನ್ನು ಸಂಗ್ರಹಿಸುತ್ತೇವೆ, ಅವುಗಳೆಂದರೆ:',
        privacy_collect_1: 'ವೈಯಕ್ತಿಕ ಗುರುತು (ಹೆಸರು, ಮೊಬೈಲ್ ಸಂಖ್ಯೆ)',
        privacy_collect_2: 'ಕೃಷಿ ವಿವರಗಳು ಮತ್ತು ಸ್ಥಳ',
        privacy_collect_3: 'ವಹಿವಾಟಿನ ಇತಿಹಾಸ ಮತ್ತು ಬಿಡ್ಡಿಂಗ್ ಡೇಟಾ',
        privacy_use_title: 'ಮಾಹಿತಿಯ ಬಳಕೆ',
        privacy_use_desc: 'ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ಈ ಕೆಳಗಿನವುಗಳಿಗಾಗಿ ಬಳಸಲಾಗುತ್ತದೆ:',
        privacy_use_1: 'ನಮ್ಮ ಸೇವೆಗಳನ್ನು ಒದಗಿಸಲು ಮತ್ತು ನಿರ್ವಹಿಸಲು.',
        privacy_use_2: 'ಬಳಕೆದಾರರ ಗುರುತನ್ನು ಪರಿಶೀಲಿಸಲು ಮತ್ತು ವಂಚನೆ ತಡೆಯಲು.',
        privacy_use_3: 'ಮಾರುಕಟ್ಟೆಯ ಒಳನೋಟಗಳನ್ನು ನೀಡಲು ಡೇಟಾವನ್ನು ವಿಶ್ಲೇಷಿಸಲು.',
        privacy_use_4: 'ರೈತರು ಮತ್ತು ಖರೀದಿದಾರರ ನಡುವೆ ಸಂವಹನ ಸುಲಭಗೊಳಿಸಲು.',
        privacy_sharing_title: 'ಮಾಹಿತಿ ಹಂಚಿಕೆ',
        privacy_sharing_desc: 'ನಾವು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ಮಾರಾಟ ಮಾಡುವುದಿಲ್ಲ. ವಹಿವಾಟು ಪೂರ್ಣಗೊಳಿಸಲು ಮಾತ್ರ ಅಗತ್ಯ ಮಾಹಿತಿಯನ್ನು ಹಂಚಿಕೊಳ್ಳುತ್ತೇವೆ (ಉದಾಹರಣೆಗೆ ಖರೀದಿದಾರರಿಗೆ ರೈತರ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನೀಡುವುದು).',
        privacy_rights_title: 'ನಿಮ್ಮ ಹಕ್ಕುಗಳು',
        privacy_rights_desc: 'ನಿಮ್ಮ ವೈಯಯಿಕ ಮಾಹಿತಿಯನ್ನು ಬದಲಾಯಿಸಲು ಅಥವಾ ಅಳಿಸಲು ನಿಮಗೆ ಹಕ್ಕಿದೆ. ಡೇಟಾ ಸುರಕ್ಷತೆಗಾಗಿ ನಾವು ಅತ್ಯಾಧುನಿಕ ಸುರಕ್ಷತಾ ಕ್ರಮಗಳನ್ನು ಅನುಸರಿಸುತ್ತೇವೆ.',
        approved_gov: 'ಭಾರತ ಸರ್ಕಾರದಿಂದ ಅನುಮೋದಿಸಲಾಗಿದೆ',
        all_rights_reserved: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ',
        staff_access: 'ಸಿಬ್ಬಂದಿ ಲಾಗಿನ್',
        join_agribid_cta: 'ಇಂದೇ AgriBid ಸೇರಿ ಮತ್ತು ನಿಮ್ಮ ಕಠಿಣ ಪರಿಶ್ರಮಕ್ಕೆ ಪ್ರತಿಫಲ ಪಡೆಯಿರಿ.',
        register_free: 'ಉಚಿತವಾಗಿ ನೋಂದಾಯಿಸಿ',
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('en');

    useEffect(() => {
        const saved = localStorage.getItem('agribid_lang') as Language;
        if (saved) setLanguageState(saved);
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('agribid_lang', lang);
    };

    const toggleLanguage = () => {
        let next: Language = 'en';
        if (language === 'en') next = 'hi';
        else if (language === 'hi') next = 'kn';
        else next = 'en';

        setLanguage(next);
    };

    const t = (key: string) => {
        return (translations[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
